# Generated by Django 3.2.2 on 2021-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CTF開始時間'),
        ),
    ]
