# Generated by Django 3.2.4 on 2021-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210615_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(editable=False, verbose_name='アカウント作成日'),
        ),
    ]
