# Generated by Django 3.2.2 on 2021-05-12 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import quizzes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.CharField(max_length=100, unique=True, verbose_name='Quiz number')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Quiz Title')),
                ('statement', models.TextField(blank=True, null=True, verbose_name='Quiz Statement')),
                ('flag', models.CharField(max_length=100, unique=True, validators=[quizzes.models.FlagValidator()], verbose_name='Flag')),
                ('difficulty', models.IntegerField(verbose_name='Difficulty')),
                ('point', models.IntegerField(verbose_name='Point')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True, verbose_name='quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quiz_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Solved date')),
                ('elapsed_time', models.TimeField(verbose_name='Elapsed time')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(related_name='quiz', to='quizzes.QuizCategory'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.ManyToManyField(related_name='quiz', to='quizzes.QuizFile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='solved_users',
            field=models.ManyToManyField(related_name='solved_quiz', through='quizzes.Solved', to=settings.AUTH_USER_MODEL),
        ),
    ]
