# Generated by Django 3.2.2 on 2021-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfile',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.ManyToManyField(null=True, related_name='quiz', to='quizzes.QuizFile'),
        ),
    ]
