# Generated by Django 3.2.2 on 2021-05-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210512_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Quiz categories'},
        ),
        migrations.AlterModelOptions(
            name='solved',
            options={'verbose_name': 'Solved user', 'verbose_name_plural': 'Solved users'},
        ),
    ]
