# Generated by Django 3.2.2 on 2021-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20210512_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='category_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Category'),
        ),
    ]
