# Generated by Django 3.2.2 on 2021-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20210517_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='quizzes.QuizFile'),
        ),
    ]
