# Generated by Django 3.2.2 on 2021-05-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solved',
            name='elapsed_time',
        ),
    ]
