# Generated by Django 3.2.2 on 2021-06-13 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_remove_solved_elapsed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAppendedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='quizzes.quizcategory'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='quizzes.QuizAppendedUrl'),
        ),
    ]
