# Generated by Django 3.2.4 on 2021-06-15 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20210613_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quizappendedurl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='quizfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='solved',
            name='solved_datetime',
            field=models.DateTimeField(editable=False, verbose_name='Solved date'),
        ),
    ]
