# Generated by Django 3.2.15 on 2022-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_extra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is extra'),
        ),
    ]
