# Generated by Django 3.2.15 on 2022-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_auto_20220901_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish at'),
        ),
    ]
