# Generated by Django 3.2.15 on 2022-09-09 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0014_alter_quiz_is_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='quizcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='solved',
            old_name='solved_datetime',
            new_name='solved_at',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='solved_users',
            field=models.ManyToManyField(related_name='solved_quizzes', through='quizzes.Solved', to=settings.AUTH_USER_MODEL),
        ),
    ]
