# Generated by Django 3.2.15 on 2022-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_auto_20220909_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.PositiveIntegerField(verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='point',
            field=models.PositiveIntegerField(verbose_name='Point'),
        ),
    ]
