# Generated by Django 3.2.15 on 2022-09-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_submitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitlog',
            name='solved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.solved'),
        ),
    ]
