# Generated by Django 3.2.15 on 2022-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_alter_configuration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='field',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
