# Generated by Django 3.2.15 on 2022-09-19 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_alter_configuration_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
